# Generated by Django 4.0.6 on 2022-07-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.DateField()),
                ('gender', models.CharField(max_length=50)),
                ('degree', models.TextField(max_length=50)),
                ('address', models.TextField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='picture/%Y/%m/%d')),
            ],
        ),
    ]
